name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install g++ -y

      - name: Download and run build-wrapper
        run: |
          curl -sSL -o build-wrapper.zip https://binaries.sonarsource.com/Distribution/sonar-build-wrapper/sonar-build-wrapper-6.56.0.6147-linux.zip
          unzip build-wrapper.zip
          ./sonar-build-wrapper-6.56.0.6147-linux/build-wrapper-linux-x86-64 --out-dir bw-output g++ -std=c++11 -o ejecutable C贸digo/main.cpp C贸digo/Cliente.cpp C贸digo/Factura.cpp

      - name: Download SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=A00841976_ProyectoIntegrador \
            -Dsonar.sources=C贸digo \
            -Dsonar.cfamily.build-wrapper-output=bw-output \
            -Dsonar.host.url=https://sonarqube.felipecastillorendon.online \
            -Dsonar.login=$SONAR_TOKEN
